### ISSUE TITLE
Issue on page /content/exploratory_notebooks/facebook_notebook.html

### ISSUE THREAD

**Issue by narjiss18** [networkx/nx-guides#112] opened 2023-07-04 20:36 UTC
Your issue content here.

**Comment by rossbar** [comment] 2023-07-05 08:59
@narjiss18 it looks like the body of the issue is missing. I will go ahead and close this - if you intended to mention something specific, please reopen with updated info!

**Closed by rossbar** 2023-07-05 08:59 UTC
